name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Copy configuration and rebuild
        run: |
          /run/wrappers/bin/sudo -E /run/current-system/sw/bin/cp configuration.nix /etc/nixos/configuration.nix
          /run/wrappers/bin/sudo -E /run/current-system/sw/bin/nixos-rebuild switch
